# Generated by Django 3.0.8 on 2020-09-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200910_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_photo',
            field=models.ImageField(upload_to='pp/', verbose_name='PP'),
        ),
    ]
