# Generated by Django 3.0.8 on 2020-09-04 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.CharField(max_length=200)),
                ('upload', models.FileField(upload_to='homework', verbose_name='Ödev Dosyası')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('finish_date', models.DateTimeField()),
                ('Teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teacher_ID')),
            ],
        ),
    ]
