# Generated by Django 3.0.8 on 2020-09-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20200913_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='content',
            field=models.FileField(blank=True, upload_to='exam'),
        ),
    ]
