# Generated by Django 3.0.8 on 2020-09-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20200913_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='content',
            field=models.FileField(blank=True, upload_to='homework'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.FileField(blank=True, upload_to='lesson'),
        ),
    ]
