# Generated by Django 3.0.8 on 2020-09-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_auto_20200913_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
